In [1]:
import numpy as np
import glob
import pandas as pd
import time
from numpy import loadtxt
from io import StringIO  

In [2]:
def concat(df, sec_df):
    df=pd.concat([df,sec_df])
    df.index=np.arange(0,len(df))
    return df

In [3]:
df=None
for i,name in enumerate(glob.glob('../26*.csv')):
    if i ==0:
        df = pd.read_csv(name,index_col=0)
    else:
        df=concat(df,pd.read_csv(name,index_col=0))

In [2]:
def string_to_array(string):
    string = string.replace("]", "").replace("[", "").replace("\n","").replace(" ","").replace("."," ")
    #k = '['+k+']'
    c = StringIO(string)

    ar=loadtxt(c)
    return ar.reshape((8,8,12))

In [5]:
len(df)

129431

In [3]:
df=pd.read_csv("chess_dataset.csv")
len(df)

1056507

In [5]:
vrijeme=time.time()
df["board"]=df["board"].apply(string_to_array)
elapsed_time=time.time()-vrijeme
print(f"Elapsed time: seconds - {elapsed_time:.2f}, minutes - {elapsed_time/60:.2f}")

Elapsed time: seconds - 323.74, minutes - 5.40


In [9]:
df["board"][0].shape

(8, 8, 12)

In [10]:
df2.to_csv("chess_dataset.csv",index=False)

In [20]:
df2 = concat(df1,df)

In [22]:
df1

fromPosition  toPosition  \
board                                                                          
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...            50          34   
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...            51          43   
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...            34          27   
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...            57          42   
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...            62          45   
...                                                          ...         ...   
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...            45          30   
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...            30          20   
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...            61          59   
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...            59          61   
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...            43          34   

                                                    player  
board                                                       
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...       0  
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...       0  
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...       0  
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...       0  
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...       0  
...                                                    ...  
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...       0  
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...       0  
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...       0  
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...       0  
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0. ...       0  

[927076 rows x 3 columns]

In [11]:
df["board"]=df["board"].apply(string_to_array)

In [7]:
df.to_csv("chess_dataset.csv",index=False)

In [13]:
df["board"][0]

array([[[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0

In [27]:
df1.head()

board  fromPosition  \
0  [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            50   
1  [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            51   
2  [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            34   
3  [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            57   
4  [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            62   

   toPosition  player  
0          34       0  
1          43       0  
2          27       0  
3          42       0  
4          45       0

In [28]:
df2.head()

board  fromPosition  \
0  [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            52   
1  [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            51   
2  [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            61   
3  [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            62   
4  [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            60   

   toPosition  player  
0          36       0  
1          43       0  
2          52       0  
3          45       0  
4          62       0

In [29]:
k=pd.concat([df1,df2])

In [31]:
k.index=np.arange(0,len(k))

In [32]:
k

board  fromPosition  \
0      [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            50   
1      [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            51   
2      [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            34   
3      [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            57   
4      [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            62   
...                                                  ...           ...   
38531  [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            29   
38532  [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            42   
38533  [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            38   
38534  [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            51   
38535  [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n  [0....            55   

       toPosition  player  
0              34       0  
1              43       0  
2              27       0  
3              42       0  
4              45       0  
...           ...     ...  
38531          37       1  
38532          51       1  
38533          46       1  
38534          55       1  
38535          53       1  

[38536 rows x 4 columns]